In [2]:
import pandas as pd


In [3]:
import numpy as np

In [ ]:
# creating a 2D arrray


In [94]:
z = np.array([[2,3,4], [5,6,8]])

In [13]:
print(z)

[[2 3 5]
 [4 7 8]]


In [16]:
s = np.array([[5,6,7],[5,7,9]])

# numpy functions


In [ ]:
arange
reshape
zeros
ones
full
linespace
random


In [19]:
#arrange
A10 = np.arange(10)
A10
print(A10)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
B10 = A10.reshape(-1,1)
print(A10,'\n', B10)

[[0 1 2 3 4]
 [5 6 7 8 9]] 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [29]:
print('The shape of 1d array x =', B10.shape)

The shape of 1d array x = (10, 1)


In [26]:
A10 = B10.reshape(2,5)
A10

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
np_zeros = np.zeros((2,3))
np_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np_ones = np.ones((2,3))
np_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np_full = np.full((2,3),4)
np_full

array([[4, 4, 4],
       [4, 4, 4]])

In [47]:
np_eye = np.eye(6,6)
np_eye

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [49]:
np_linspace = np.linspace(0,10, num=6)
np_linspace

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [77]:
#create an array filled with random values between 0 and 1
np_rand1 = np.random.random_sample((2,3))
np_rand2 = np.random.rand(2,3)
np_rand3 = np.random.randint(10, size=(5,3))
np.save('array_data.npy', np_rand3)
np_rand1
np_rand2
np_rand3


array([[2, 4, 8],
       [8, 2, 6],
       [9, 9, 3],
       [9, 6, 8],
       [3, 2, 0]])

In [78]:
np_rand2

array([[0.00745499, 0.25672147, 0.06508167],
       [0.22546874, 0.7552356 , 0.13671968]])

In [79]:
np_rand3

array([[2, 4, 8],
       [8, 2, 6],
       [9, 9, 3],
       [9, 6, 8],
       [3, 2, 0]])

# Asccessing element of numpy array

In [81]:
#To access an element in a two dimensional array you need to specify an index for both the row and the column

In [85]:
print(z)
z[1,0]
[[1,2],[3,4]]

[[2 3 5]
 [4 7 8]]


[[1, 2], [3, 4]]

In [88]:
p = np.array([[1,2],[3,4]])
p

array([[1, 2],
       [3, 4]])

In [95]:
p = z[1][0]
p

5

In [96]:
p =(z[0:1, 0])
p

array([2])

In [100]:
#Transpose
p.T

array([2])